language: node_js
node_js:
  - "8.9"
before_install:
  - npm install -g npm@5.7
install:
  - npm ci
  - npm run build
  - npm run bootstrap
script:
  - npm run ci-test
  - npm run ci-codecov
  - npm run lint
